# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.8)
   message(FATAL_ERROR "CMake >= 3.0.0 required")
endif()
if(CMAKE_VERSION VERSION_LESS "3.0.0")
   message(FATAL_ERROR "CMake >= 3.0.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 3.0.0...3.29)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_cmake_targets_defined "")
set(_cmake_targets_not_defined "")
set(_cmake_expected_targets "")
foreach(_cmake_expected_target IN ITEMS digiscope-api::protobuf-api digiscope-api::event-packet digiscope-api::networker digiscope-api::digitizer-wrapper digiscope-api::valijson_interface digiscope-api::rapidjson_interface)
  list(APPEND _cmake_expected_targets "${_cmake_expected_target}")
  if(TARGET "${_cmake_expected_target}")
    list(APPEND _cmake_targets_defined "${_cmake_expected_target}")
  else()
    list(APPEND _cmake_targets_not_defined "${_cmake_expected_target}")
  endif()
endforeach()
unset(_cmake_expected_target)
if(_cmake_targets_defined STREQUAL _cmake_expected_targets)
  unset(_cmake_targets_defined)
  unset(_cmake_targets_not_defined)
  unset(_cmake_expected_targets)
  unset(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT _cmake_targets_defined STREQUAL "")
  string(REPLACE ";" ", " _cmake_targets_defined_text "${_cmake_targets_defined}")
  string(REPLACE ";" ", " _cmake_targets_not_defined_text "${_cmake_targets_not_defined}")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_cmake_targets_defined_text}\nTargets not yet defined: ${_cmake_targets_not_defined_text}\n")
endif()
unset(_cmake_targets_defined)
unset(_cmake_targets_not_defined)
unset(_cmake_expected_targets)


# Compute the installation prefix relative to this file.
get_filename_component(_IMPORT_PREFIX "${CMAKE_CURRENT_LIST_FILE}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
if(_IMPORT_PREFIX STREQUAL "/")
  set(_IMPORT_PREFIX "")
endif()

# Create imported target digiscope-api::protobuf-api
add_library(digiscope-api::protobuf-api STATIC IMPORTED)

set_target_properties(digiscope-api::protobuf-api PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/protobuf-api"
  INTERFACE_LINK_LIBRARIES "protobuf::libprotobuf;gRPC::grpc;gRPC::grpc++"
)

if(NOT CMAKE_VERSION VERSION_LESS "3.23.0")
  target_sources(digiscope-api::protobuf-api
    INTERFACE
      FILE_SET "HEADERS"
      TYPE "HEADERS"
      BASE_DIRS "${_IMPORT_PREFIX}/include/protobuf-api"
      FILES "${_IMPORT_PREFIX}/include/protobuf-api/api.pb.h" "${_IMPORT_PREFIX}/include/protobuf-api/api.grpc.pb.h"
  )
else()
  set_property(TARGET digiscope-api::protobuf-api
    APPEND PROPERTY INTERFACE_INCLUDE_DIRECTORIES
      "${_IMPORT_PREFIX}/include/protobuf-api"
  )
endif()

# Create imported target digiscope-api::event-packet
add_library(digiscope-api::event-packet STATIC IMPORTED)

set_target_properties(digiscope-api::event-packet PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/event-packet"
  INTERFACE_LINK_LIBRARIES "Qt6::Core;Qt6::Network"
)

if(NOT CMAKE_VERSION VERSION_LESS "3.23.0")
  target_sources(digiscope-api::event-packet
    INTERFACE
      FILE_SET "HEADERS"
      TYPE "HEADERS"
      BASE_DIRS "${_IMPORT_PREFIX}/include/event-packet"
      FILES "${_IMPORT_PREFIX}/include/event-packet/buffers/packetbuffer.h" "${_IMPORT_PREFIX}/include/event-packet/buffers/packetparser.h" "${_IMPORT_PREFIX}/include/event-packet/buffers/splituppacketassembler.h" "${_IMPORT_PREFIX}/include/event-packet/buffers/wavewaveformseparator.h" "${_IMPORT_PREFIX}/include/event-packet/packets/consistentchannelspectrum16.h" "${_IMPORT_PREFIX}/include/event-packet/packets/consistentchannelspectrum32.h" "${_IMPORT_PREFIX}/include/event-packet/packets/detectron2dnetworkpacket.h" "${_IMPORT_PREFIX}/include/event-packet/packets/detectronstatisticnetworkpacket.h" "${_IMPORT_PREFIX}/include/event-packet/packets/eventpackettype.h" "${_IMPORT_PREFIX}/include/event-packet/packets/phanetworkpacket.h" "${_IMPORT_PREFIX}/include/event-packet/packets/psdnetworkpacket.h" "${_IMPORT_PREFIX}/include/event-packet/packets/spectrumtype.h" "${_IMPORT_PREFIX}/include/event-packet/packets/waveformnetworkpacket.h" "${_IMPORT_PREFIX}/include/event-packet/packetwrappers/eventdata.h" "${_IMPORT_PREFIX}/include/event-packet/packetwrappers/eventpacket.h" "${_IMPORT_PREFIX}/include/event-packet/packetwrappers/eventpacketheader.h"
  )
else()
  set_property(TARGET digiscope-api::event-packet
    APPEND PROPERTY INTERFACE_INCLUDE_DIRECTORIES
      "${_IMPORT_PREFIX}/include/event-packet"
  )
endif()

# Create imported target digiscope-api::networker
add_library(digiscope-api::networker STATIC IMPORTED)

set_target_properties(digiscope-api::networker PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/networker"
  INTERFACE_LINK_LIBRARIES "Qt6::Core;Qt6::Network;digiscope-api::event-packet;digiscope-api::protobuf-api"
)

if(NOT CMAKE_VERSION VERSION_LESS "3.23.0")
  target_sources(digiscope-api::networker
    INTERFACE
      FILE_SET "HEADERS"
      TYPE "HEADERS"
      BASE_DIRS "${_IMPORT_PREFIX}/include/networker"
      FILES "${_IMPORT_PREFIX}/include/networker/commanddeviceconnector.h" "${_IMPORT_PREFIX}/include/networker/commandsupportflags.h" "${_IMPORT_PREFIX}/include/networker/maintainingdeviceconnector.h" "${_IMPORT_PREFIX}/include/networker/networkenums.h" "${_IMPORT_PREFIX}/include/networker/networkworker.h" "${_IMPORT_PREFIX}/include/networker/threaded.h"
  )
else()
  set_property(TARGET digiscope-api::networker
    APPEND PROPERTY INTERFACE_INCLUDE_DIRECTORIES
      "${_IMPORT_PREFIX}/include/networker"
  )
endif()

# Create imported target digiscope-api::digitizer-wrapper
add_library(digiscope-api::digitizer-wrapper STATIC IMPORTED)

set_target_properties(digiscope-api::digitizer-wrapper PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/digitizer-wrapper"
  INTERFACE_LINK_LIBRARIES "Qt6::Core;Qt6::Network;Qt6::StateMachine;\$<LINK_ONLY:digiscope-api::event-packet>;\$<LINK_ONLY:digiscope-api::networker>;\$<LINK_ONLY:digiscope-api::valijson_interface>;\$<LINK_ONLY:digiscope-api::rapidjson_interface>"
)

if(NOT CMAKE_VERSION VERSION_LESS "3.23.0")
  target_sources(digiscope-api::digitizer-wrapper
    INTERFACE
      FILE_SET "HEADERS"
      TYPE "HEADERS"
      BASE_DIRS "${_IMPORT_PREFIX}/include/digitizer-wrapper"
      FILES "${_IMPORT_PREFIX}/include/digitizer-wrapper/device.h" "${_IMPORT_PREFIX}/include/digitizer-wrapper/devicemanagerbase.h" "${_IMPORT_PREFIX}/include/digitizer-wrapper/devicemanagerwrapper.h" "${_IMPORT_PREFIX}/include/digitizer-wrapper/devicesettingsdefines.h" "${_IMPORT_PREFIX}/include/digitizer-wrapper/devicesettingstablemodel.h" "${_IMPORT_PREFIX}/include/digitizer-wrapper/devicestatemachine.h" "${_IMPORT_PREFIX}/include/digitizer-wrapper/digitizerinteractor.h" "${_IMPORT_PREFIX}/include/digitizer-wrapper/firmwaresettingsmodelrepositorybase.h" "${_IMPORT_PREFIX}/include/digitizer-wrapper/firmwaresettingstablemodel.h" "${_IMPORT_PREFIX}/include/digitizer-wrapper/fwsettingsvalidator.h" "${_IMPORT_PREFIX}/include/digitizer-wrapper/iabstractsettingsmodel.h" "${_IMPORT_PREFIX}/include/digitizer-wrapper/networkmediator.h" "${_IMPORT_PREFIX}/include/digitizer-wrapper/settingitem.h"
  )
else()
  set_property(TARGET digiscope-api::digitizer-wrapper
    APPEND PROPERTY INTERFACE_INCLUDE_DIRECTORIES
      "${_IMPORT_PREFIX}/include/digitizer-wrapper"
  )
endif()

# Create imported target digiscope-api::valijson_interface
add_library(digiscope-api::valijson_interface INTERFACE IMPORTED)

# Create imported target digiscope-api::rapidjson_interface
add_library(digiscope-api::rapidjson_interface INTERFACE IMPORTED)

# Load information for each installed configuration.
file(GLOB _cmake_config_files "${CMAKE_CURRENT_LIST_DIR}/digiscope-api-targets-*.cmake")
foreach(_cmake_config_file IN LISTS _cmake_config_files)
  include("${_cmake_config_file}")
endforeach()
unset(_cmake_config_file)
unset(_cmake_config_files)

# Cleanup temporary variables.
set(_IMPORT_PREFIX)

# Loop over all imported files and verify that they actually exist
foreach(_cmake_target IN LISTS _cmake_import_check_targets)
  if(CMAKE_VERSION VERSION_LESS "3.28"
      OR NOT DEFINED _cmake_import_check_xcframework_for_${_cmake_target}
      OR NOT IS_DIRECTORY "${_cmake_import_check_xcframework_for_${_cmake_target}}")
    foreach(_cmake_file IN LISTS "_cmake_import_check_files_for_${_cmake_target}")
      if(NOT EXISTS "${_cmake_file}")
        message(FATAL_ERROR "The imported target \"${_cmake_target}\" references the file
   \"${_cmake_file}\"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   \"${CMAKE_CURRENT_LIST_FILE}\"
but not all the files it references.
")
      endif()
    endforeach()
  endif()
  unset(_cmake_file)
  unset("_cmake_import_check_files_for_${_cmake_target}")
endforeach()
unset(_cmake_target)
unset(_cmake_import_check_targets)

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
