#pragma once

namespace network
{

enum class NETWORK_DEVICE_COMMAND
{
    CONNECT_DEVICE = 0,
    DISCONNECT_DEVICE,
    UPDATE_DEVICE_FIRMWARE,
    UPDATE_DEVICE_ROOT_FS,
    REBOOT_DEVICE,
    GET_FIRMWARE_SETTINGS_SCHEMA,
    GET_FIRMWARE_SETTINGS_VALUES,
    SET_FIRMWARE_SETTINGS_VALUES,
    GET_PROTOCOL_VERSION,
    START_DEVICE_MEASUREMENT,
    START_DEVICE_MEASUREMENT_WITH_TIME,
    STOP_DEVICE_MEASUREMENT,
    FORGET_DEVICE
};

enum class NETWORK_DEVICE_EVENT
{
    NEW_DEVICE_DISCOVERED = 0,
    DEVICE_CONNECT_SUCCESS,
    DEVICE_CONNECTED_SAME,
    DEVICE_CONNECTED_OTHER,
    DEVICE_DISCONNECT_SUCCESS,
    DEVICE_ALREADY_DISCONNECTED,
    DEVICE_FIRMWARE_UPDATED,
    DEVICE_FIRMWARE_UPDATE_FAILED,
    DEVICE_ROOT_FS_UPDATED,
    DEVICE_ROOT_FS_UPDATE_FAILED,
    DEVICE_REBOOTED,
    FIRMWARE_SETTINGS_SCHEMA_RECEIVED,
    FIRMWARE_SETTINGS_VALUES_RECEIVED,
    FIRMWARE_SETTINGS_VALUES_APPLIED,
    PROTOCOL_VERSION_RECEIVED,
    DEVICE_MEASUREMENT_STARTED,
    DEVICE_MEASUREMENT_START_FAILED,
    DEVICE_MEASUREMENT_WITH_TIME_STARTED,
    DEVICE_MEASUREMENT_WITH_TIME_START_FAILED,
    DEVICE_MEASUREMENT_STOPPED,
    DEVICE_MEASUREMENT_STOP_FAILED,
    DEVICE_CONNECTION_LOST
};

} // namespace network
